config/routes.rb
Rails.application.routes.draw do
  resource :login, only: [:new, :create, :destroy] do
    delete "logout", to: "logins#destroy"
  end
  resources :users, only: [:new, :create]
  resources :products, only: [:index]
  resource :cart, only: [:show] do
    post :buy, on: :collection
  end
  resources :order_items, only: [:create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    enum status: [:in_progress, :shipped, :cancelled]

    belongs_to :user, optional: true
    has_many :order_items, dependent: :destroy

    before_create :set_order_status
    before_save :set_total

    def valid_ttl?
        self.updated_at > 2.days.ago
    end

    private

    def set_order_status
        self.status = :in_progress
    end

    def set_total
        self.total = order_items.sum { |oi| oi.quantity * oi.unit_price }
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates_presence_of :quantity, numericality: { only_integer: true, greater_than: 0 }
  validates_presence_of :product
  validates_presence_of :order

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  def update_unit_price(price)
    self[:last_unit_price] = self[:unit_price]
    self[:unit_price] = price
  end

  private

  def finalize
    self[:last_unit_price] = unit_price unless self[:last_unit_price]
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name, :price

  has_many :order_items

  after_save :update_in_progress_orders

  def update_in_progress_orders
    self.order_items.each do |oi|
      oi.update_unit_price(self.price)
      oi.save
      oi.order.save
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # encrypt password
  has_secure_password

  has_many :orders

  validates_presence_of :name, :username, :password_digest
  validates_length_of :password, minimum: 6, maximum: 20, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_order
  before_action :current_user

  helper_method :current_order

  def current_order
    @current_order = 
      if !session[:order_id].nil?
        order = Order.find(session[:order_id])
        if !order.valid_ttl?
          order.update(status: :cancelled)
          Order.new(total: 0)
        else
          order
        end
      else
        Order.new(total: 0)
      end
  end

  def current_user
    @current_user = 
      if !session[:user_id].nil?
        User.find(session[:user_id])
      else
        User.new
      end
  end

  private


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = @current_order.order_items.order(:id)
  end

  def buy
    @current_order.update(status: :shipped)
    new_order = @current_user.orders.new
    session[:order_id] = new_order.id
    redirect_to root_url, flash: { info: 'Your order has been delivered' }
  end
end

app/controllers/concerns/authentication_helper.rb
class AuthenticationHelper
    attr_reader :session
    def initialize(session)
        @session = session
    end

    def authenticate(user)
        @session[:user_id] = user.id
        load_user_order(user)
    end

    def load_user_order(user)
        if actual_order_has_items? && actual_order_still_valid?
            actual_order.user = user
            actual_order.save
        else
            last_user_order = user.orders.last
            @session[:order_id] = last_user_order.id if last_user_order
        end
    end

    def actual_order_has_items?
        return false unless @session[:order_id] 
        actual_order && actual_order.order_items.count > 0
    end

    def actual_order_still_valid?
        return false unless @session[:order_id] 
        actual_order && actual_order.valid_ttl?
    end

    def actual_order
        @actual_order ||= Order.find(@session[:order_id])
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(username: params[:username])
        if user && user.authenticate(params[:password])
            AuthenticationHelper.new(session).authenticate(user)
            redirect_to root_url, flash: { info: 'Logged in!' }
        else
            flash.now[:warning] = 'Email or password is invalid'
            render :new
        end
    end

     def destroy
        session[:user_id] = nil
        session[:order_id] = nil
        redirect_to root_url
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    if @order_item = @current_order.order_items.where(product_id: order_item_params["product_id"]).first
      @order_item.quantity += order_item_params["quantity"].to_i
      @order_item.save
    else
      @order_item = @current_order.order_items.new(order_item_params)
    end
    @current_order.user = @current_user unless @current_user.id.nil?
    @current_order.save
    session[:order_id] = @current_order.id
  end

  def update
    @order_item = @current_order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @current_order.user = @current_user unless @current_user.id.nil?
    @current_order.save
    @order_items = @current_order.order_items.order(:id)
  end

  def destroy
    @order_item = @current_order.order_items.find(params[:id])
    @order_item.destroy
    @current_order.user = @current_user unless @current_user.id.nil?
    @current_order.save
    @order_items = @current_order.order_items.order(:id)
  end

  private

  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = OrderItem.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to root_url unless @current_user.id.nil?
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    AuthenticationHelper.new(session).authenticate(@user)
    redirect_to redirect_to_param["redirect_to"] if redirect_to_param["redirect_to"]
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation)
  end

  def redirect_to_param
    params.permit(:redirect_to)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">
    <div class="row">
        <div class="col-xs-8">
            <h4>
                <%= product.name %>
            </h4>
        </div>
        <div class="col-xs-4">
            <%= form_for order_item, remote: true do |f| %>
                <% if order_item.last_unit_price != order_item.unit_price %>
                    <div class="row">
                        <div class="col-xs-12 text-right">
                            Price changed from
                            <span style="color: green">
                                <%= number_to_currency order_item.last_unit_price %>
                            </span>
                            to
                        </div>
                    </div>
                <% end %>
                <h4 class="text-right">Unit Price:
                    <span style="color: green">
                        <%= number_to_currency order_item.unit_price %>
                    </span>
                </h4>
                <div class="row">
                    <div class="col-xs-4">
                        <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
                        <%= f.hidden_field :product_id, value: product.id %>
                    </div>
                    <div class="col-xs-8 text-right">
                        <div class="btn-group">
                            <%= f.submit "Update Quantity", class: "btn btn-primary" %>
                            <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
                        </div>
                    </div>
                </div>
                <h4 class="text-right">Total Price:
                    <span style="color: green">
                        <%= number_to_currency order_item.total_price %>
                    </span>
                </h4>
            <% end %>
        </div>
    </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
    <div class="alert alert-danger">
        <ul>
            <% @order_item.errors.full_messages.each do |msg| %>
                <li>
                    <%= msg %>
                </li>
            <% end %>
        </ul>
    </div>
<% end %>
<% if @order_items.size == 0 %>
    <p class="text-center">
        There are no items in your shopping cart. Please
        <%= link_to "go back", root_path %> and add some items to your cart.
    </p>
<% else %>
    <% @order_items.each do |order_item| %>
        <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
    <% end %>
    <div class="row">
        <div class="col-xs-12 text-right">
            <% if @current_user.id.nil? %>
                <%= link_to "Log in", new_login_path, class: "btn btn-link" %> or <%= link_to "Sign up", new_user_path, class: "btn btn-link" %> to finish.
            <% else %>
                <%= link_to "Buy cart", buy_cart_path, method: :post, class: "btn btn-success" %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
    <%= render "shopping_cart" %>   
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{@current_order.order_items.sum { |oi| oi.quantity }} Items in Cart ( #{number_to_currency @current_order.total} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_user.html.erb
<% if @current_user.id.nil? %>
    <%= link_to "Log in", new_login_path, class: "btn btn-link" %>
    <%= link_to "Sign up", new_user_path, class: "btn btn-link" %>
<% else %>
    <%= @current_user.name %> <%= link_to "log out", logout_login_path, class: "btn btn-link", method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awesome Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js' %>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row" style="background-color: #ccc;">
        <div class="col-xs-6">
          <h1>Awesome Store</h1>
        </div>
        <div class="col-xs-6 text-right">
          <div class="row">
            <div class="col-xs-12">
              <%= render 'layouts/user' %>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <h1 class="cart-text">
                <%= render 'layouts/cart_text' %>
              </h1>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <%= link_to "Home", root_url, class: "btn btn-link" %>
        </div>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/logins/new.html.erb
<div class="row">
    <div class="col-xs-6 col-xs-offset-3">
        <h2>Login</h2>

        <%= form_tag login_path do %>
            <div class="form-group">
                <%= label_tag :username %>
                <%= text_field_tag :username, params[:username], class: "form-control" %>
            </div>
            <div class="form-group">
                <%= label_tag :password %>
                <%= password_field_tag :password, nil, class: "form-control" %>
            </div>
            <%= submit_tag "Login", class: "btn btn-default" %>
        <% end %>
    </div>
</div>

app/views/order_items/create.js.erb
<% if @current_order.errors.any? || @order_item.errors.any? %>
    alert("not valid.")
<% else %>
    $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <div class="caption">
            <h3>
                <%= product.name %>
            </h3>
            <p>
                <h4 class="text-success text-center">
                    <%= number_to_currency product.price %>
                </h4>
            </p>
            <p class="text-center">
                <%= form_for order_item, remote: true do |f| %>
                    <div class="input-group">
                        <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
                        <div class="input-group-btn">
                            <%= f.hidden_field :product_id, value: product.id %>
                            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
                        </div>
                    </div>
                <% end %>
            </p>
        </div>
    </div>
</div>

app/views/products/index.html.erb
<div class="row">
<% @products.each do |product| %>
  <%= render "product_row", product: product, order_item: @order_item %>
<% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="row">
    <div class="col-xs-6 col-xs-offset-3">
        <h2>Sign Up</h2>
        
        <%= form_for @user do |f| %>
            <% if @user.errors.any? %>
                <div class="error_messages">
                    <h2>Form is invalid</h2>
                    <ul>
                        <% @user.errors.full_messages.each do |message| %>
                            <li>
                                <%= message %>
                            </li>
                            <% end %>
                    </ul>
                </div>
            <% end %>
        
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :username %>
                <%= f.text_field :username, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
            <%= f.submit "Sign Up", class: "btn btn-default" %>
        <% end %>
    </div>
</div>